version: '3.8'

networks:
  sigcoges:
  proxy_1:
    external: true

services:

  sigcoges_db:
    image: mariadb:10.5
    container_name: sigcoges_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: sigcoges_db
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3383:3306
    networks:
      - sigcoges

  sigcoges_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - sigcoges_db
    ports:
      - 8083:80
    environment:
      UPLOAD_LIMIT: 300M
    networks:
      - sigcoges
      - proxy_1

  sigcoges_app:
    container_name: sigcoges_app
    restart: always
    build:
      context: ./docker
    depends_on:
      - sigcoges_db
    environment:
      - APP_ENV=prod
      - MAILER_DSN=gmail
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@sigcoges_db:3306/sigcoges_db
    volumes:
      - ./app:/var/www/html
    networks:
      - sigcoges

  sigcoges_nginx:
    container_name: sigcoges_nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8085:80
    depends_on:
      - sigcoges_app
    networks:
      - sigcoges
      - proxy_1

