version: '3.8'

networks:
  internal:
  proxy:
    external: true

services:

  dbsigcoges:
    image: mariadb:10.5
    container_name: dbsigcoges
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: sigcoges_db
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3307:3306
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - dbsigcoges
    ports:
      - 83:80
    environment:
      UPLOAD_LIMIT: 300M
    networks:
      - internal
      - proxy

  appsigcoges:
    container_name: appsigcoges
    restart: always
    build:
      context: ./docker
    depends_on:
      - dbsigcoges
    environment:
      - APP_ENV=prod
      - MAILER_DSN=gmail
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@dbsigcoges:3306/sigcoges_db
    volumes:
      - ./app:/var/www/html
    networks:
      - internal

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 82:80
    depends_on:
      - appsigcoges
    networks:
      - internal
      - proxy

